<?php

/**
 * @file
 * Contains formation_rest.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function formation_rest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the formation_rest module.
    case 'help.page.formation_rest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Rest for formation') . '</p>';
      return $output;

    default:
  }
}
